What joy, I figured this error out! This one in particular:
/home/luiserebii/hydrosnowflake_marketplace_coupons/contracts/marketplace/features/Coupons.sol:9:1: DeclarationError: Identifier already declared.
import '../../ein/token/ERC721/address/AddressSnowflakeERC721Mintable.sol';
/home/luiserebii/hydrosnowflake_marketplace_coupons/contracts/ein/access/Roles.sol:7:1: The previous declaration is here:
library Roles {
Compilation failed. See above.

Basically, the I was using the defined library in Roles.sol in both the zeppelin/access location and the ein/access location. The following GitHub issue is relevant here: https://github.com/aragon/aragonOS/issues/411

As is neatly explained: "Unfortunately, solc doesn't know how to handle cases where the contract names are the same, but come from two different locations."

Excellent